#!/bin/bash
#PBS -N IDLFIELD2D
#PBS -q batch
#PBS -l walltime=2:00:00,mem=2000mb,nodes=1
#PBS -p 1023
#PBS -m a
#

cd /cl/home01/hr/SULLIVAN
export DISPLAY=localhost:0.0
/usr/local/bin/idl idl_field2d

exit
