#!/usr/bin/perl
# file: KILL 
# job:  kill all jobs for a certain user and mode on amd02--amd24
# ---------------------
$uname = "artb";
$mode  = "VL";
#
system("touch temp");
for ($i=1; $i<=16; $i = $i+1) {
	system("rm -f temp");
	system("touch temp");
	$n = "o$i";

	$cname = "$n";
	$command = "ssh $cname ps aux |grep $uname |grep $mode > temp";
	print "$command\n";
	system("$command");
	system("cat temp");
	open(IN,"temp") || die "cannot open temp for reading $!";
	while( defined($line1=<IN>) ){
        	chop($line1);
        	@field1 = split(/ +/, $line1);
        	$e=$field1[1];
		print "$e\n";
		$command2 = "ssh $cname kill -9 $e";
		print "$command2\n";
		system("$command2");
	}
	system("rm -f temp");
}

# eof
