#!/usr/bin/perl
# ---------------------
#
$uname = "artb";
$dir = "test";
$mode  = "00";
#
system("touch temp");
for ($i=2; $i<=16; $i = $i+1) {

	system("rm -f temp");
	system("touch temp");
	$n = "o$i";
	$command = "ls /scratch/$n/$uname/$dir | grep $mode > temp";
	system("$command");

	open(IN,"temp") || die "cannot open temp for reading $!";
	while( defined($line1=<IN>) ){
	    $command2 = "ln -s /scratch/$n/$uname/$dir/$line1";
	    print "$command2\n";
	    system("$command2");
	}

	system("rm -f temp");
}

# eof
