#!/usr/bin/perl
# file: MKDIR
# job:  make directories on nodes
# ---------------------

$uname = "artb";
$dir = "test";
#
for ($i=2; $i<=16; $i = $i+1) {

	$n = "o$i";
	$command = "mkdir /scratch/$n/$uname/$dir";
	print "$command\n";
	system("$command");

}

# eof
