#!/bin/tcsh

# AUTHORS:    H. Ruhl, R. Schopper
# FILE:       POST-PROCESSOR SHELL SCRIPT FOR IONS
# DATE:       08.08.2000


# TIME FILE FILTER


set u = ''


foreach z ( `ls | sed -ne 's/00000ion'$u'//p'` )

   # FILE SELECTION

   echo > II; echo e1 >> II; echo $u$z >> II; echo q >> II; cat II | ./SELECT.x

   set pe = 'I'$u$z'.data'
   if ( -e $pe ) then
      gzip -f $pe
   endif

   # CONTROL OF FILE EXISTENCE

   set pe = 'I'$u$z'.data.gz'

   if ( -e $pe ) then

      echo 'DATA SET COMPLETE!' >> IFILES

   endif

end
exit
