#!/bin/tcsh

# AUTHORS:    H. Ruhl, R. Schopper
# FILE:       POST-PROCESSOR SHELL SCRIPT FOR ELECTRONS
# DATE:       08.08.2000


# TIME FILE FILTER


set u = ''


foreach z ( `ls | sed -ne 's/00000electron'$u'//p'` )

   # FILE SELECTION

   echo > EE; echo d1 >> EE; echo $u$z >> EE; echo q >> EE; cat EE | ./SELECT.x

   set pe = 'E'$u$z'.data'
   if ( -e $pe ) then
      gzip -f $pe
   endif

   # CONTROL OF FILE EXISTENCE

   set pe = 'E'$u$z'.data.gz'

   if ( -e $pe ) then

      echo 'DATA SET COMPLETE!' >> EFILES

   endif

end
exit
