#!/bin/bash

#############################################################
#
# Author:   Hartmut Ruhl
# File:     PBS sript for starting the PSC code
# Date:     11/03/2005
#
# This script links the files belonging to the simulation
# to the home directory. It does not matter if the files
# are distributed of n filesystems, where 1<=n<=np or if
# they are located in a single file system. The script
# moves old checkpointing files into the backup and new
# ones into the new startup files. This way jobs can be
# safely restarted.
#
# Instructions: -Adapt the directory list for FSN to
#                the directories your data reside in.
#               -Adapt 'nodes' to the node number
#                required by your application.
#  
#############################################################

#PBS -N MAIN
#PBS -q batch
#PBS -l walltime=120:00,mem=2000mb,nodes=32
#PBS -p 1023
#PBS -m a
#

NODENR=32
NAME='SULLIVAN'

HOME='/cl/data01/hr/'$NAME
cd $HOME

mpirun -np $NODENR $HOME/VLA.x >> $HOME/VLA.data


if [ -e $HOME/okfile ]
then

# In case the job has finished without errors soft links are
# generated across the distributed file systems. The list for
# FSN has to be adapted to those filesystems the data reside in.

for FSN in "/cl/data01/hr/$NAME" "/cl/data02/hr/$NAME" "/cl/data03/hr/$NAME" "/cl/data04/hr/$NAME" \
           "/cl/data05/hr/$NAME" "/cl/data06/hr/$NAME" "/cl/data07/hr/$NAME" "/cl/data08/hr/$NAME" \
           "/cl/data09/hr/$NAME" "/cl/data10/hr/$NAME" "/cl/data11/hr/$NAME" "/cl/data12/hr/$NAME" \
           "/cl/data13/hr/$NAME" "/cl/data14/hr/$NAME" "/cl/data15/hr/$NAME" "/cl/data16/hr/$NAME" \
           "/cl/data17/hr/$NAME" "/cl/data18/hr/$NAME" "/cl/data19/hr/$NAME" "/cl/data20/hr/$NAME" \
           "/cl/data21/hr/$NAME" "/cl/data22/hr/$NAME" "/cl/data23/hr/$NAME" "/cl/data24/hr/$NAME" \
           "/cl/data25/hr/$NAME" "/cl/data26/hr/$NAME" "/cl/data27/hr/$NAME" "/cl/data28/hr/$NAME" \
           "/cl/data29/hr/$NAME" "/cl/data30/hr/$NAME" "/cl/data31/hr/$NAME" "/cl/data32/hr/$NAME" \
           "/cl/data33/hr/$NAME" "/cl/data34/hr/$NAME" "/cl/data35/hr/$NAME" "/cl/data36/hr/$NAME" \
           "/cl/data37/hr/$NAME" "/cl/data38/hr/$NAME" "/cl/data39/hr/$NAME" "/cl/data40/hr/$NAME" \
           "/cl/data41/hr/$NAME" "/cl/data42/hr/$NAME" "/cl/data43/hr/$NAME" "/cl/data44/hr/$NAME" \
           "/cl/data45/hr/$NAME" "/cl/data46/hr/$NAME" "/cl/data47/hr/$NAME" "/cl/data48/hr/$NAME"

do
   for FN in `ls $FSN | sed -ne 's/CPNEW//p'`
   do
      for BN in `ls $FSN | sed -ne 's/'$FN'atom//p'`
      do
         ln -s $FSN/$FN'atom'$BN $HOME
      done
      for BN in `ls $FSN | sed -ne 's/'$FN'electron//p'`
      do
         ln -s $FSN/$FN'electron'$BN $HOME
      done
      for BN in `ls $FSN | sed -ne 's/'$FN'ion//p'`
      do
         ln -s $FSN/$FN'ion'$BN $HOME
      done
      for BN in `ls $FSN | sed -ne 's/'$FN'tfield//p'`
      do
         ln -s $FSN/$FN'tfield'$BN $HOME
      done
      for BN in `ls $FSN | sed -ne 's/'$FN'pfield//p'`
      do
         ln -s $FSN/$FN'pfield'$BN $HOME
      done
      for BN in `ls $FSN | sed -ne 's/'$FN'poynting//p'`
      do
         ln -s $FSN/$FN'poynting'$BN $HOME
      done
      for BN in `ls $FSN | sed -ne 's/'$FN'collision//p'`
      do
         ln -s $FSN/$FN'collision'$BN $HOME
      done
      for BN in `ls $FSN | sed -ne 's/'$FN'kec//p'`
      do
         ln -s $FSN/$FN'kec'$BN $HOME
      done

   done
done

# The old check pointing files are moved into the backup check pointing 
# files. The server list SN has to be adapted those servers that have 
# the data in their filesystems.
 
for SN in "fi01" "fi02" "fi03" "fi04" \
          "fi05" "fi06" "fi07" "fi08" \
          "fi09" "fi10" "fi11" "fi12" \
          "fi13" "fi14" "fi15" "fi16" \
          "fi17" "fi18" "fi19" "fi20" \
          "fi21" "fi22" "fi23" "fi24" \
          "fi25" "fi26" "fi27" "fi28" \
          "fi29" "fi30" "fi31" "fi32" \
          "fi33" "fi34" "fi35" "fi36" \
          "fi37" "fi38" "fi39" "fi40" \
          "fi41" "fi42" "fi43" "fi44" \
          "fi45" "fi46" "fi47" "fi48"

do
   for FN in `rsh $SN ls /data/hr/$NAME | sed -ne 's/CPOLD//p'`
   do
      rsh $SN mv -f /data/hr/$NAME/$FN'CPOLD' /data/hr/$NAME/$FN'CPBAC'
   done
done

# The new check pointing files are moved into the old check pointing files. 
# The server list SN has to be adapted those servers that have the data in 
# their filesystems.

for SN in "fi01" "fi02" "fi03" "fi04" \
          "fi05" "fi06" "fi07" "fi08" \
          "fi09" "fi10" "fi11" "fi12" \
          "fi13" "fi14" "fi15" "fi16" \
          "fi17" "fi18" "fi19" "fi20" \
          "fi21" "fi22" "fi23" "fi24" \
          "fi25" "fi26" "fi27" "fi28" \
          "fi29" "fi30" "fi31" "fi32" \
          "fi33" "fi34" "fi35" "fi36" \
          "fi37" "fi38" "fi39" "fi40" \
          "fi41" "fi42" "fi43" "fi44" \
          "fi45" "fi46" "fi47" "fi48"

do
   for FN in `rsh $SN ls /data/hr/$NAME | sed -ne 's/CPNEW//p'`
   do
      rsh $SN mv -f /data/hr/$NAME/$FN'CPNEW' /data/hr/$NAME/$FN'CPOLD'
   done
done

fi

# The job is restarted from the old check pointing files
# if it has not yet finished.

if [ ! -e ./endfile ]
then
   if [ -e ./okfile ]
   then

      rm ./okfile
      /usr/local/bin/qsub ./vlaexec

   fi
fi

exit
