
#include <psc_fields_as_c.h>
#include <psc_particles_as_double.h>

#define psc_collision_sub_ops psc_collision_double_ops
#define psc_output_fields_item_coll_stats_ops psc_output_fields_item_coll_stats_double_ops
#define psc_output_fields_item_coll_rei_ops psc_output_fields_item_coll_rei_double_ops

#include "psc_collision_common.cxx"
