
#include <psc_fields_as_single.h>
#include <psc_particles_as_single.h>

#define psc_collision_sub_ops psc_collision_single_ops
#define psc_output_fields_item_coll_stats_ops psc_output_fields_item_coll_stats_single_ops
#define psc_output_fields_item_coll_rei_ops psc_output_fields_item_coll_rei_single_ops

#include "psc_collision_common.cxx"
