#!/bin/tcsh

# AUTHORS:    H. Ruhl, R. Schopper
# FILE:       POST-PROCESSOR SHELL SCRIPT FOR ATOMS
# DATE:       08.08.2000


# TIME FILE FILTER


set u = ''


foreach z ( `ls | sed -ne 's/00000atom'$u'//p'` )

   # FILE SELECTION

   echo > AA; echo f1 >> AA; echo $u$z >> AA; echo q >> AA; cat AA | ../src/SELECT

   set pe = 'A'$u$z'.data'
   if ( -e $pe ) then
      gzip -f $pe
   endif

   # CONTROL OF FILE EXISTENCE

   set pe = 'A'$u$z'.data.gz'

   if ( -e $pe ) then

      echo 'DATA SET COMPLETE!' >> AFILES

   endif

end
exit
