#!/bin/tcsh

# AUTHORS:    H. Ruhl, R. Schopper
# FILE:       POST-PROCESSOR SHELL SCRIPT FOR TIME RESOLVED FIELDS
# DATE:       08.08.2000


# TIME FILE FILTER


set u = ''


foreach z ( `ls | sed -ne 's/00000pfield'$u'//p'` )


# SELECT THE FIELDS FOR OUTPUT HERE


   foreach fieldt (eyt ezt net hxt)


   # FILE SELECTION


   echo > PP; echo a1 >> PP; echo $fieldt >> PP; echo $u$z >> PP; echo q >> PP; cat PP | ./SELECT.x
   set field = $fieldt$u$z'.data'

   if ( -e $field ) then
      gzip -f $field
   endif

   end

   # CONTROL OF FILE EXISTENCE

   set field = $fieldt$u$z'.data.gz'


   if ( -e $field ) then
       echo 'DATA SET COMPLETE!' >> PFILES
   endif

end
exit
