#!/bin/tcsh

# AUTHORS:    H. Ruhl, R. Schopper
# FILE:       POST-PROCESSOR SHELL SCRIPT FOR TIME RESOLVED FIELDS
# DATE:       08.08.2000


# TIME FILE FILTER


set u = ''


foreach z ( `ls | sed -ne 's/00000tfield'$u'//p'` )

# SELECT THE FIELDS FOR OUTPUT HERE

   foreach fieldt (ey2t ez2t net bxt jyit jzit jyeyit jzezit)

   # FILE SELECTION


   echo > TT; echo b1 >> TT; echo $fieldt >> TT; echo $u$z >> TT; echo q >> TT; cat TT | ../src/SELECT
   set field = 'TAV-'$fieldt$u$z'.data'

   if ( -e $field ) then
      gzip -f $field
   endif

   end

   # CONTROL OF FILE EXISTENCE

   set field = 'TAV-'$fieldt$u$z'.data.gz'


   if ( -e $field ) then
       echo 'DATA SET COMPLETE!' >> TFILES
   endif

end
exit
