
#include "fields_item_jeh.hxx"
#include "fields_item_fields.hxx"

FieldsItemFieldsOps<Item_j_nc> psc_output_fields_item_j_nc_ops;
FieldsItemFieldsOps<Item_j_cc> psc_output_fields_item_j_ops;
FieldsItemFieldsOps<Item_j_ec> psc_output_fields_item_j_ec_ops;

FieldsItemFieldsOps<Item_e_nc> psc_output_fields_item_e_nc_ops;
FieldsItemFieldsOps<Item_e_cc> psc_output_fields_item_e_ops;
FieldsItemFieldsOps<Item_e_ec> psc_output_fields_item_e_ec_ops;

FieldsItemFieldsOps<Item_h_nc> psc_output_fields_item_h_nc_ops;
FieldsItemFieldsOps<Item_h_cc> psc_output_fields_item_h_ops;
FieldsItemFieldsOps<Item_h_fc> psc_output_fields_item_h_fc_ops;

FieldsItemFieldsOps<Item_poyn> psc_output_fields_item_poyn_ops;
FieldsItemFieldsOps<Item_e2> psc_output_fields_item_e2_ops;
FieldsItemFieldsOps<Item_h2> psc_output_fields_item_h2_ops;

FieldsItemFieldsOps<Item_jdote> psc_output_fields_item_jdote_ops;
FieldsItemFieldsOps<Item_divb> psc_output_fields_item_divb_ops;
FieldsItemFieldsOps<Item_divj<MfieldsStateDouble, MfieldsC>> psc_output_fields_item_divj_ops;

